//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRecipeApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    
    public partial class Recipe
    {
        public int recipeID { get; set; }

        [DisplayName("Name")]
        public string recipeName { get; set; }

        [DisplayName("Ingredients")]
        public string recipeIngredients { get; set; }

        [DisplayName("Upload File")]
        public string recipeImagePath { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
